version: '3'
services:
  client:
    container_name: client
    build: ./client
    ports:
      - '8080:8080'
    environment:
      - 'API_URL=http://localhost:3000/'
  server:
    container_name: server
    build: ./server
    ports:
      - '3000:3000'
    environment:
      - 'DATABASE_URL=mariadb://rsyslog:password@192.168.0.186:3306/Syslog'
